### ISSUE TITLE
Problem in Compile calc1 Example

### ISSUE THREAD

**Issue by QuestionPython** [smvv/pybison#9]
i want to compile calc1 of https://github.com/smvv/pybison using python 2.7 but show error.

My OS is GNU/Linux Ubuntu 16.10-64bit(GNOME)

calc test ==> is right.

calc1 test ==> have problem.

=============

information of flex :
```
root@system:/home/guest/Project/pybison-master# flex -V
flex 2.6.1
```
information of bison :
```
root@system:/home/guest/Project/pybison-master# bison -V
bison (GNU Bison) 3.0.4
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
information of gcc :
```
root@system:/home/guest/Project/pybison-master# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.2.0-5ubuntu12' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) 
```
information of cython :
```
root@system:/home/guest/Project/pybison-master# cython -V
Cython version 0.24.1
```
Error Of PyCharm IDE:

```tmp.tab.c: In function ‘yyparse’:
tmp.tab.c:1302:16: warning: implicit declaration of function ‘yylex’ [-Wimplicit-function-declaration]
       yychar = yylex ();
                ^~~~~
tmp.tab.c:2063:9: warning: implicit declaration of function ‘yyerror’ [-Wimplicit-function-declaration]
         yyerror (yymsgp);
         ^~~~~~~
./tmp.l:3:5: error: redefinition of ‘yylineno’
 int yylineno = 0;
     ^~~~~~~~
lex.yy.c:340:5: note: previous definition of ‘yylineno’ was here
 int yylineno = 1;
     ^~~~~~~~
./tmp.l: In function ‘yylex’:
./tmp.l:36:10: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘char *’ [-Wformat=]
 .       { printf("unknown char %c ignored, yytext=0x%lx\n", yytext[0], yytext); /* ignore bad chars */}
          ^
./tmp.l: At top level:
./tmp.l:41:1: warning: return type defaults to ‘int’ [-Wimplicit-int]

 ^     
Traceback (most recent call last):
  File "/home/guest/PycharmProjects/Interpreter/main.py", line 251, in <module>
    p = Parser(keepfiles=0)
  File "/usr/local/lib/python2.7/dist-packages/bison/__init__.py", line 159, in __init__
    self.engine = ParserEngine(self)
  File "bison_.pyx", line 123, in bison_.ParserEngine.__init__
  File "bison_.pyx", line 144, in bison_.ParserEngine.openCurrentLib
  File "bison_.pyx", line 525, in bison_.ParserEngine.buildLib
  File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'cc' failed with exit status 1

Process finished with exit code 1
```

How can I fix this problem?

**Comment by smvv** [comment]
I think that removing this line: https://github.com/smvv/pybison/blob/master/examples/calc1/calc1.py#L210 should fix the problem.

**Comment by QuestionPython** [comment]
Tank you. :+1: , this work now. :1st_place_medal:

**Comment by questionpython** [comment]
Tank you. :+1: , this now work.

**Comment by questionpython** [comment]
Also i Send a Mail To You.
Please Check Them.
Tanks.

**Comment by smvv** [comment]
@questionpython are you Erfan? Sorry, I do not have time to work on new projects due to my work.

I'll mark this issue as closed and resolved.
